mode: commit
min_length: 3
allowed:
  - acl
  - aspell
  - repo
  - yaml
  - config
  - Github
  - Gitlab
  - env
  - failsafe
  - golang
  - mkdir
  - WORKDIR
  - apk
  - ENTRYPOINT
  - ubuntu
  - golangci
  - sudo
  - releaser
  - backend
  - backends
  - frontend
  - frontends
  - tcp
  - crd
  - linter
  - linters
  - tls
  - lifecycle
  - passthrough
  - ssl
  - unix
  - parallelize
  - maxconn
