#!/usr/bin/with-contenv sh

/dlv exec /haproxy-ingress-controller \
  --continue \
  --listen=:40143 \
  --headless=true \
  --log=true \
  --api-version=2 \
  --accept-multiclient \
  -- --with-s6-overlay ${EXTRA_OPTIONS}
